### ISSUE TITLE
Support  USDC for the local demo

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cape#1011]
As discussed with @jillrcarlson

**Comment by philippecamacho** [comment]
Source code of USDC contract: https://github.com/centrehq/centre-tokens
Source code "all in one place": https://etherscan.io/address/0xa2327a938febf5fec13bacfb16ae10ecbc4cbdcf#code

**Comment by philippecamacho** [comment]
To deploy "manually" the USD contract do:
* Run cape-demo-local in the cape repository
* `git clone  https://github.com/centrehq/centre-tokens`
* `cd centre-tokens`
* `yarn install`
* `yarn migrate --network development`

The USDC contract seems to be the one deployed at step 7., e.g:
```
7_deploy_master_minter.js
=========================
deploying MasterMinter for fiat token at 0xA51c1fc2f0D1a1b8494Ed1FE312d7C3a78Ed91C0

   Deploying 'MasterMinter'
   ------------------------
   > transaction hash:    0xd71373e91cf9993fac46e16d980e5ab148266236b27ca40eca26fa453a68ef4d
   > Blocks: 0            Seconds: 0
   > contract address:    0xE6E340D132b5f46d1e472DebcD681B2aBc16e57E
   > block number:        323
   > block timestamp:     1652144189
   > account:             0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
   > balance:             904625697166532776746648320380374280103671755200316906558.259269351133085717
   > gas used:            1272234 (0x1369aa)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.02544468 ETH

master minter deployed at 0xE6E340D132b5f46d1e472DebcD681B2aBc16e57E
reassigning owner to 0x3e5e9111ae8eb78fe1cc3bb8915d5d461f3ef9a9
All done.
```

TODO: set config.js correctly in order to be able to mint USDC tokens.

**Comment by sveitser** [comment]
If we use `--network development` the settings in `config.js` are ignored.

https://github.com/centrehq/centre-tokens/blob/0d3cab14ebd133a83fc834dbd48d0468bdf0b391/migrations/7_deploy_master_minter.js#L17-L22

**Comment by philippecamacho** [comment]
Will not be implemented. Replaced by #1024.
