### ISSUE TITLE
Display in the relayer logs the content of a CAP block sent to the CAPE contract

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cape#1038]
In order to "visualize" than the transaction information is hidden in CAPE, we can output the content of CAP block just before the relayer sends it in the logs.

**Comment by sveitser** [comment]
Not quite sure what format would be suitable for this task. If we debug print the block it looks like this in the logs. The first one is our own `CapeBlock` the second one is the Ethereum struct `CapeBlock`

![image](https://user-images.githubusercontent.com/1040871/168262644-8dae4cb3-f35b-468a-8b1e-1957888957c7.png)

Is this what you had in mind?

**Comment by philippecamacho** [comment]
> Not quite sure what format would be suitable for this task. If we debug print the block it looks like this in the logs. The first one is our own `CapeBlock` the second one is the Ethereum struct `CapeBlock`
> 
> ![image](https://user-images.githubusercontent.com/1040871/168262644-8dae4cb3-f35b-468a-8b1e-1957888957c7.png)
> 
> Is this what you had in mind?

Yes, exactly, thanks!
