### ISSUE TITLE
Decrease size of roots array in the CAPE contract

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cape#1055]
Currently set to 1000. This causes the wallet to take a lot of time to recover from a transaction being rejected.
1000 is too much, 10 sounds too little (@sveitser: "If the system were really busy this corresponds to 3-4 ethereum blocks. Or about 1 minute."), how many roots should we keep in the contract?

**Comment by philippecamacho** [comment]
What about 20? @jbearer @sveitser

**Comment by nyospe** [comment]
50 seems like a reasonable to conservative length. Five minutes. 20 feels on the short end of reasonable.

**Comment by philippecamacho** [comment]
40
