### ISSUE TITLE
Set manual gas limit in relayer to avoid out of gas errors

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cape#1056]
6M should be ok.

**Comment by sveitser** [comment]
On 2nd thought, the 6M suggested may not be enough. It needs to cover 1 note and up to 10 deposits. I will try to estimate how much that is.

**Comment by sveitser** [comment]
Crediting 10 deposits with an empty block costs 5,058,242 gas.

**Comment by sveitser** [comment]
```
transfer=1 mint=0 freeze=0 gas used: 4782806
transfer=0 mint=1 freeze=0 gas used: 4389595
transfer=0 mint=0 freeze=1 gas used: 4432718
```
So the max is 4,782,806.

We currently don't have a test that does 10 deposits + a transfer in one block. I will choose 10M greater than cost(10 deposits) + cost(1 transfer). In reality it will be cheaper because only one merkle tree update is being done.

**Comment by sveitser** [comment]
I forgot about burn notes. The gas usage of the burn note submission in our unwrapping test is `4,943,889`. For arbitrary tokens this could be anything though. It may be better to just use estimate gas and add something to that. Or we could consider supporting tokens that use unreasonable amounts of gas out of scope.
