### ISSUE TITLE
Increase faucet gateway timeout

### ISSUE THREAD

**Issue by jbearer** [EspressoSystems/cape#1092]
The faucet now transfers multiple records per request (2, in the Goerli deployment) which is much friendlier for users as it allows recipients to then make two simultaneous transfers with their two records. However, since it takes longer to generate the 2 transfers instead of 1, we are seeing gateway timeout errors on faucet requests.

**Comment by philippecamacho** [comment]
Faucet: 3 to 4 min.
The load balancer timeouts need to be updated as well.
