### ISSUE TITLE
Improve user guide with some trouble shooting section.

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cape#1154]
See https://www.notion.so/espressosys/sync-08415a62fcfb46eaa6143d0490ddb550#3e05f4704edb4955845ab99280fccb40

**Comment by philippecamacho** [comment]
@pictographer be clear about things that need to be done just once.

**Comment by jillrcarlson** [comment]
Other (from @shenkeyao): 
Clicked the "Welcome" section expecting to read intro about CAPE but there wasn't one. Would be nice to have a brief intro or a link to an intro.
It would be good to have a "Through this user guide, you would be able to create a wallet, sponsor an asset…" section to summarize the expected outcomes before "Get started".

**Comment by philippecamacho** [comment]
See also https://www.notion.so/espressosys/sync-08415a62fcfb46eaa6143d0490ddb550#ad976d87d21741858f4f61506f329b05
