### ISSUE TITLE
Extract data from the CAPE contract

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cape#1155]
* Number of wrap/unwrap
* Number of tx of each type
* Number of discrete wallet that have interacted with the contract

**Comment by philippecamacho** [comment]
Generate a spreadsheet with the raw data so that people can aggregated.

**Comment by sveitser** [comment]
@philippecamacho If you wanna give it a try see https://github.com/EspressoSystems/cape-analytics

**Comment by philippecamacho** [comment]
It worked!

**Comment by philippecamacho** [comment]
Potential feature: run the script incrementally.

**Comment by philippecamacho** [comment]
For sponsor transaction count how many viewing/freezing keys are used.

**Comment by philippecamacho** [comment]
As [discussed](https://www.notion.so/espressosys/Prod-ENG-call-June-29th-91052fa33c4a457293af5bd123a666c7#e2e43468829b4ce29fbfac928a7fceb7), no more features for now.
