### ISSUE TITLE
Nonce errors in relayer transaction submission

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/cape#1173]
We have about 30x per day: `replacement transaction underpriced`. This is quite noisy. We could retry these transactions a few times if this happens or compute the nonce manually. The second solution is a bit more involved though as we may need to handle the case where the local nonce goes out of sync.

**Comment by philippecamacho** [comment]
> @philippecamacho we were thinking it would be worth to add the retry to have 1) less noisy logs 2) less user facing errors. Let me know what you think.
> 
> Although 1) could also be "fixed" by just ignoring these errors in datadog.

The retry solution looks good to me.
