### ISSUE TITLE
Cannote create wallet using docker image

### ISSUE THREAD

**Issue by sorcer1122** [EspressoSystems/cape#1200]
Hello, trying to create a wallet using this docker file - https://www.espressosys.com/cape/docker-compose.yaml

getting the following error

![image](https://user-images.githubusercontent.com/15838362/179324268-606ca478-8c91-4313-9ba0-bb48755d7720.png)

**Comment by sveitser** [comment]
We had some issues with the backend last week. Does this error still occur now?

**Comment by sveitser** [comment]
Please re-open if the problem is still there.
