### ISSUE TITLE
Investigate Faucet double spend issue

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cape#1203]
See  https://www.notion.so/espressosys/Engineering-Weekly-559fe2b6ea864bdc9321f22b284f7905#82a8189026e04e5e85240ba2ef713e42

**Comment by sveitser** [comment]
Put some notes [on notion](https://www.notion.so/espressosys/Faucet-attempted-nullifier-double-spend-4ba539cb07ba45e5951ece488d9fcf65).

**Comment by philippecamacho** [comment]
cc @tri-joe

**Comment by philippecamacho** [comment]
Closing for now, assuming #1206 will solve the problem.
