### ISSUE TITLE
Address Book mapping addresses to encryption public keys

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cape#189]
See specification at https://www.notion.so/translucence/Mapping-addresses-encryption-public-keys-498265172e2642d790c90da282cc2249

- [x] #291
- [x] #292
- [x] #293
- [x] #294
- [x] #295 
- [x] Implement tests
- [x] Rename to Address Book
- [x] #504
- [x] #505

**Comment by sveitser** [comment]
This should be "done", so closing.
