### ISSUE TITLE
Rest API for serving queries from other components Relayer, Memo service and Wallet

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cape#254]

**Comment by philippecamacho** [comment]
Is this not done already @kmchicoine , @nyospe or maybe it is a duplicate of #244?

**Comment by nyospe** [comment]
I believe it is effectively a duplicate of 244. There may be endpoints needed by the Relayer in the future that are not yet present (new nullifiers since a point in time, specifically) but since the full Relayer is not part of this deliverable, we should close this.
