### ISSUE TITLE
Allow more flexible burn transaction

### ISSUE THREAD

**Issue by jbearer** [EspressoSystems/cape#265]
See https://translucence.zulipchat.com/#narrow/stream/311688-CAPE/topic/Burn.20outputs

- [ ] Allow change outputs
- [ ] Allow multiple inputs

**Comment by philippecamacho** [comment]
Link https://translucence.zulipchat.com/#narrow/stream/311688-CAPE/topic/Burn.20outputs is broken (even replacing translucence with espresso) cc @jbearer

**Comment by jbearer** [comment]
Oh, the retention policy got it.

To summarize, the Rust model of the contract used to only support burns with exactly 2 inputs and 2 outputs, so this is what the wallet did. We later discovered that the real contract had no such limitation (only requiring that the second output be the burned record) so we created this ticket to lift the restriction in the wallet.
