### ISSUE TITLE
EQS API: obtain an AAP transaction by hash

### ISSUE THREAD

**Issue by jbearer** [EspressoSystems/cape#455]
* `get_transaction_by_hash(hash: Commitment<CapeTransition>) -> CommittedCapeTransition`
    - Required for wallet transaction tracking, which is especially important for synchronizing between different wallets to avoid race conditions in tests
    - Should fail with a reasonable error message if `hash` does not identify a previously committed transaction
    - `CommittedCapeTransition` is as defined in #247

**Comment by philippecamacho** [comment]
Is not it a duplicate of #247? @nyospe @kmchicoine

**Comment by nyospe** [comment]
> 

It is not, in fact, a duplicate. The two endpoints have a different index. This one lets the wallet find a transaction it submitted, if it has been committed, without yet having processed the event for its commit.

**Comment by nyospe** [comment]
This is the one I need to add a new TaggedBase64 wrapper type for.
