### ISSUE TITLE
Comprehensive documentation review

### ISSUE THREAD

**Issue by pictographer** [EspressoSystems/cape#464]
After the various bits of documentation are complete, we should read all the documentation that outside users will see, looking for inconsistencies and gaps.

- [x] cargo doc `cargo doc --no-deps --open`
   - [x] address book
   - [x] cap_rust_sandbox
   - [x] cape_wallet
   - [x] cape_workflow
   - [x] eqs
   - [x] faucet
   - [x] relayer
   - [x] wallet_api
   - [x] wallet_cli
- [x] Solidity docgen
- [x] README.md, etc. for all the repos
   - [x] cape
   - [x] cap
   - [x] reef
   - [x] cape-ui
   - [x] seahorse 
   - [x] jellyfish
   - [x] key-set
   - [x] arbitrary-wrappers
   - [x] tagged-base64
   - [x] AT-spec
   - [x] commit
- [x] Lower priority: Git Hub Issues

**Comment by sveitser** [comment]
@pictographer I had to disable documentation for the address book binary to avoid a file collision (https://github.com/EspressoSystems/cape/pull/877/commits/a196de728b91617c084f23a4d9587ece6beb3501). Does it even make sense to build the rust doc for binary targets? The documentation looks much less useful than what `the-binary --help`  produces.

**Comment by philippecamacho** [comment]
As mentioned in Zulip I mistakenly pushed to main. The commits to review are
a3261bb8070e7caa56b155af5cfe7b8553b5ed43
0419d0db2ddfe419b90f9121aaa98dcc403e4253
aba5ed98f974e712062ecc0ac0af5299078e7721
825336168013d113c86a0ce2788bfe0ae2b315e8
29234bed78e34a3bfbcfe3477acfe171883ce214
6838905fd31fb28f1a888fbd8d65ed0391042bdc

cc @pictographer @sveitser

**Comment by pictographer** [comment]
I've left comments on the commits above. A few need detail I don't know off hand. Most are trivial language issues and I'd be glad to make a pull request. @philippecamacho
