### ISSUE TITLE
Address book: Add finishing details including error messages

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/cape#505]

**Comment by philippecamacho** [comment]
Command line arguments are not needed.

**Comment by pictographer** [comment]
The last task for this is to [add SIGTERM and SIGINT handling](https://translucence.zulipchat.com/#narrow/stream/311688-CAPE/topic/Ctrl-c.20to.20exit.20Tide).

**Comment by sveitser** [comment]
@pictographer Since
- https://github.com/EspressoSystems/cape/pull/694

is merged. Should this be closed?
