### ISSUE TITLE
Infura account / ensure we don’t get rate limited by the infura web3 provider

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/cape#531]
We should register an account with infura that belongs to the company. In case we exceed the free tier requests we should be able to quickly update it so I think it's best to have an account with payment method already set up.

- [ ] Register account on infura: https://infura.io/register
- [ ] Create project for CAPE demo
- [ ] Get endpoint from settings page (E. g. `https://rinkeby.infura.io/v3/54a...1cfb`) this will be the `CAPE_WEB3_PROVIDER_URL` that our services use.

A free account provides 100k requests per day (source: [pricing page](https://infura.io/pricing)). I think this is likely sufficient for the demo because most requests go to the EQS and the EQS itself does not need to make that many requests.  I'm not familiar with how exactly they count requests though.

Trying to rougly estimate the number of requests we'll need below.

- If the EQS polls every 7 seconds (Ethereum block time is 15s) this is 12400 requests per day per EQS instance (of which we plan to have 2) so a total of about 25k per day. We could also consider pulling more frequently for potentially better user experience.
- One extra request per submitted txn (including faucet txns) from the relayer.
- One extra request per mined txn for fetching the Block in the EQS.

So the total number of requests should be about `25k + 2 * num_cape_txn`. Or in other words the free tier is enough for `(100k - 25k) / 2 = 37.5k txns` per day.

cc @nyospe @jbearer

**Comment by philippecamacho** [comment]
Currently using 10% of what we plan to use.
Check with @clu8 if we need more.

**Comment by sveitser** [comment]
I'm not sure where the current 10% come from. I'm only aware of the rinkeby test in the CI. If the 10% number is from there I don't think it's useful to estimate what we are going to need later.

**Comment by Ancient123** [comment]
Definitely agree on that number not being too useful. But the estimate at the beginning of this issue is probably a bit better. Although we need to add the current 10% number to that as well for total usage.
