### ISSUE TITLE
Deployment tooling for updates to docker image

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/cape#534]

**Comment by philippecamacho** [comment]
@sveitser what does this mean in practice?

**Comment by sveitser** [comment]
We need to have a workflow for getting updates to the docker images deployed to production. I think in practice for the backend services ECS will watch for updates to the images built on github and pull them and restart the services. We may want to decide if this happens automatically or if we would like a human in the loop. We may also first want to deploy to a staging environment.

For the wallet docker image I am not sure what the best way is to make sure the users are running the latest version or a version that is compatible with the backend. We should probably discuss this.

cc @Ancient123
