### ISSUE TITLE
Infrastructure for CAPE demo

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/cape#539]
- Current preference for using [AWS ECS Fargate](https://aws.amazon.com/fargate/) to host the demo.
- Do we want to use the same terraform + ansible combo as for https://github.com/SpectrumXYZ/cloud-infrastructure ?
  + Not sure if ansible is still useful with ECS (?)
- We should have a staging env that is as close of a clone of the real (to be) production env as possible.
- What are the availability requirements?
- What are the data persistence requirements?
  + Minimal relayer is stateless
  + EQS uses snapshots
  + Address book uses atomic store with files: https://github.com/EspressoSystems/cape/pull/704
- Document how code is pushed to production
  + E.g.: only code with tag release gets pushed to production (@Ancient123)

**Comment by sveitser** [comment]
Summary of the configuration: https://www.notion.so/espressosys/CAPE-Demo-configuration-820caf91aa8b4890a6b0b5310947027b

**Comment by philippecamacho** [comment]
Ping @Ancient123 when the executable of the services /docker containers are ready.
