### ISSUE TITLE
All API servers have status check monitoring

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/cape#543]
- [ ] Depends on #708. 
- [ ] relayer
- [ ] EQS
- [ ] address book
- [ ] wallet service

**Comment by philippecamacho** [comment]
What shall we do with these endpoints in practice @sveitser @Ancient123?

**Comment by philippecamacho** [comment]
Deployment scripts check all the services are up.
See https://github.com/EspressoSystems/cape-deploy/blob/main/scripts/scale-up.fish.
