### ISSUE TITLE
Support wallet recovery by mnemonic

### ISSUE THREAD

**Issue by shenkeyao** [EspressoSystems/cape#593]
Reference: [recovery flow design](https://www.figma.com/file/A7tDqu5TzLpoZiPY6rgOpV/CAPE-UI?node-id=8779%3A4127).

Pasting from Jeb's comment:

> Recovery when you still have your local files but forgot your password. This will go through the load() interface, but it acts more like creating a new wallet, since the password is not derived from the mnemonic and thus the encrypted files cannot be recovered. However, we do have access to the (unencrypted) metadata, so we can potentially be a little bit more helpful by checking if the entered recovery phrase is correct (e.g., by using the mnemonic to generate an encryption key and encrypting random bytes in the metadata, as we were doing before). Then we can, in some cases at least, generate the error message in frame "Desktop - 502".

**Comment by snipeTR** [comment]
my disk crashed, i have mnemonic words, i guess it is not possible to save my wallet. is it correct?

**Comment by snipeTR** [comment]
> Yeah, @snipeTR , the functionality to recover from a mnemonic without the keystore files exists in the backend, but for demo purposes we haven't built it into the UI yet.

Tnx for answer. Please send me info for backend way. Any docs.

**Comment by jbearer** [comment]
The backend way is not officially supported, and we won't be providing assistance with it for now. But you can go to `localhost:60000` while Docker is running, and see a list of available API endpoints. The ones you would use for recovering a wallet are `newwallet` (which lets you create new keystore files using your old mnemonic) and `recoverkey` (which will generate the same key you had in your old wallet, if you used the same mnemonic, and scan the ledger for records belonging to that key)

**Comment by snipeTR** [comment]
Thank you for this information.  I understand it is not officially supported.  I'm trying to set up a backup script.  I wonder what files we back up, and restore.  Can we run it smoothly?

**Comment by jbearer** [comment]
All the necessary files are saved in a Docker volume, so to back them up you just need to back up the `espresso` volume. Maybe you can try something like this: https://blog.ssdnodes.com/blog/docker-backup-volumes/

**Comment by snipeTR** [comment]
> The backend way is not officially supported, and we won't be providing assistance with it for now. But you can go to `localhost:60000` while Docker is running, and see a list of available API endpoints. The ones you would use for recovering a wallet are `newwallet` (which lets you create new keystore files using your old mnemonic) and `recoverkey` (which will generate the same key you had in your old wallet, if you used the same mnemonic, and scan the ledger for records belonging to that key)

man, I couldn't even figure out how to post these apis. I even reviewed your source code. Can you show me an example with a simple api? I couldn't even figure out how to enter mnemonic exactly. base64?

**Comment by snipeTR** [comment]
> > The backend way is not officially supported, and we won't be providing assistance with it for now. But you can go to `localhost:60000` while Docker is running, and see a list of available API endpoints. The ones you would use for recovering a wallet are `newwallet` (which lets you create new keystore files using your old mnemonic) and `recoverkey` (which will generate the same key you had in your old wallet, if you used the same mnemonic, and scan the ledger for records belonging to that key)
> 
> dude, I couldn't even figure out how to post these apis. I even reviewed your source code. Can you show me an example with a simple api? I couldn't even figure out how to enter mnemonic exactly. base64?
