### ISSUE TITLE
Batch inversion in public input polynomial evaluation

### ISSUE THREAD

**Issue by kilic** [EspressoSystems/cape#689]
https://github.com/EspressoSystems/cape/blob/c623d85af975d04a68b0efc2430af4b81fad629d/contracts/contracts/libraries/PolynomialEval.sol#L194

Currently for each public input there is a modexp precompile call for the inversion. Batch inversion technique would reduce this cost down to a single call.

**Comment by zhenfeizhang** [comment]
Sounds like a great idea. Will try it out. Thanks for pointing this out.

**Comment by alxiong** [comment]
Thanks @kilic for the suggestion, in face I did use the precompiled call, the `BN.invert()` is just a light inlined function for readability:

```solidity
    /// @dev Compute f^-1 for f \in Fr scalar field
    /// @notice credit: Aztec, Spilsbury Holdings Ltd
    function invert(uint256 fr) internal view returns (uint256 output) {
        bool success;
        uint256 p = R_MOD;
        assembly {
            let mPtr := mload(0x40)
            mstore(mPtr, 0x20)
            mstore(add(mPtr, 0x20), 0x20)
            mstore(add(mPtr, 0x40), 0x20)
            mstore(add(mPtr, 0x60), fr)
            mstore(add(mPtr, 0x80), sub(p, 2))
            mstore(add(mPtr, 0xa0), p)
            success := staticcall(gas(), 0x05, mPtr, 0xc0, 0x00, 0x20)
            output := mload(0x00)
        }
        require(success, "Bn254: pow precompile failed!");
    }
```
