### ISSUE TITLE
Deployment of CAPE contract and services for GUI testing purposes

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cape#734]
- [x] CAPE contract
- [x] EQS
- [x] Minimal relayer
- [x] Address Book

Note that the GUI and Wallet will run locally.

**Comment by sveitser** [comment]
This is for deployment to public testnet.

**Comment by sveitser** [comment]
We will first make the local demo work
- #738

**Comment by philippecamacho** [comment]
I think deploying everything locally is fine. The idea is to enable the developers to test the GUI without mocking components.

**Comment by philippecamacho** [comment]
* GUI team is installing nix
* Have a container for each of the services and the wallet.
* Still run the deployment from the nix-shell

**Comment by sveitser** [comment]
For the docker compose version I suggest the following

- one container per service
- one wallet-api container
- Run geth outside of docker if that's not too complicated so that we can use our existing tooling to initialize the chain and deploy the contracts.

**Comment by sveitser** [comment]
@Ancient123 I have this working but only with host networking. If we want to not use host networking it would be a bit involved and require some re-doing on how we run geth and deploy the contract.

I think the easiest might be to 

- Set up geth like we do now.
- Deploy contracts
- Shut down but keep its data directory around.
- Mount directory into the docker container to run geth with docker compose.

**Comment by philippecamacho** [comment]
@Ancient123 will work on the testing infrastructure to allow that.
Check with @pictographer to see if this works.

**Comment by philippecamacho** [comment]
@Ancient123 Deploying into the cloud will require dockerization.
