### ISSUE TITLE
add test in wallet to make sure these native tokens are transferable

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cape#763]

**Comment by shenkeyao** [comment]
There's currently a test (`test_send` in `wallet/src/wallet-api/main.rs`) for the `send` endpoint that transfers some native tokens from the faucet address to an unfunded address and verifies the balance.

@tri-joe or @sveitser (sorry not sure who of you brought up this issue), could you confirm whether this is enough for the purpose of this issue?

**Comment by jbearer** [comment]
That test uses a mock faucet. I think we want a test that uses the real faucet service and makes an HTTP request to trigger the transfer
