### ISSUE TITLE
Log service for each component with Rest API

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cape#767]
* Output to stdout/stderr
* Check that the log messages we have are sufficient / useful / needed
* Add / remove log messages accordingly

- [x] #801
- [x] #768
- [x] #769
- [x] #770
- [x] #771

**Comment by sveitser** [comment]
We can do the logging via `tide::log`. Like it's done in the address book for example.

**Comment by philippecamacho** [comment]
Let us use `tracing`
