### ISSUE TITLE
Define a log strategy across all services

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cape#801]
* What to log at each level (ERROR;WARNING,INFO,TRACE,DEBUG). Fairly standard meaning in systems programming. Check documentation of tracing crate.
* Differentiate between expected errors and non recoverable errors
* Do we want to be conservative about what constitutes a warning (e.g. TIMEOUT event once is an info, many times TIMEOUT is a warning...)

Be consistent across all the components.

**Comment by philippecamacho** [comment]
@nyospe working on notion page with recommendations.

**Comment by nyospe** [comment]
https://www.notion.so/espressosys/Guidelines-for-Logging-368b6f741b79473b80358dcbce8e6dd2

**Comment by Ancient123** [comment]
Looks good and pretty clear to me.

**Comment by sveitser** [comment]
I also think it's great. Thanks @nyospe. Closing this issue!
