### ISSUE TITLE
Backup mechanism if something goes wrong with the faucet wallet

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cape#806]
* Write an executable that generates 10 new wallets 
* Transfer initial grant to 10 wallets
* Print the mnemonics and store them somewhere

* Define how to securely backup the mnemonic (see with @sveitser)

**Comment by jbearer** [comment]
The utility to create the new wallets and transfer to them is done (`faucet-shower`). We just need to decide how we are backing up the mnemonics @sveitser @Ancient123

**Comment by philippecamacho** [comment]
@Ancient123 can use some AWS service to securely stores the mnemonic.
