### ISSUE TITLE
Handling chain/block reorganizations

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/cape#884]
Block reorganizations are quite common on goerli (https://goerli.etherscan.io/blocks_forked) so we should be able to recover from it.

A simple fix is to set the number of confirmations to a high enough number to make reorganizations of that many blocks very unlikely. This however may not provide the best user experience.

**Comment by philippecamacho** [comment]
@jbearer the wallet gets the chain information from the EQS.

**Comment by philippecamacho** [comment]
Check with Product team how many blocks we can wait for without hurting too much the user experience.

**Comment by philippecamacho** [comment]
Configure the EQS so that it waits for one or two confirmations.

**Comment by sveitser** [comment]
Closed by #912
