### ISSUE TITLE
Alerts are configured so the right people will be alerted, but only when really necessary

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cape#917]
List of tasks from 

- [x]  Infura nodes not responding (unlikely, alert users)
- [x] Running out of Goerli eth for the Relayer. 
- [x] Relayer wallet unable to submit Ethereum txns because it’s out of Ether.  Monitor wallet balance.
- [x] Relayer wallet unable to submit Ethereum txns because it messed up its nonce management ([[Relayer Nonce Management](https://www.notion.so/Relayer-Nonce-Management-d2dd901f687845518294b24277d2bd5e)](https://www.notion.so/Relayer-Nonce-Management-d2dd901f687845518294b24277d2bd5e)). Not easy to detect.
- [x] Corruption of the EQS store. Can be fixed by re-building.
- [x] Corruption of the faucet store. Can be fixed by re-building from mnemonic.
- [x] EQS runs out of memory.
- [x] All services running out of memory or using CPU 100% for a long time
- [x] Unknown bugs in services and contract.
- [x] Services panic.
- [x] General health end points are not responding 
    - [x] Internal
    - [x] External

**Comment by Ancient123** [comment]
` Running out of infura credits (goerli eth). We should monitor the balance.`
There are no Infura APIs for checking this unfortunately.

**Comment by sveitser** [comment]
LGTM.
