### ISSUE TITLE
EQS panics if HTTP requests to provider fail

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/cape#949]
Requests could fail for a variety of reasons so I think it would be desirable to return an Error and retry instead of panicking right away.

https://github.com/EspressoSystems/cape/blob/4a0de582065b27df2592fe210576e67639f4e220/eqs/src/eth_polling.rs#L129

https://github.com/EspressoSystems/cape/blob/4a0de582065b27df2592fe210576e67639f4e220/eqs/src/eth_polling.rs#L152

The second request could also hit infura limits of 10k events or over 10 seconds query time: https://docs.infura.io/infura/networks/ethereum/json-rpc-methods/eth_getlogs#limitations

**Comment by philippecamacho** [comment]
Potential solution: change the EQS so that it fetches not all the blocks at once.
If the EQS needs to fetch more than 10k events it will not be able to start at all.

**Comment by Ancient123** [comment]
Related to this, they should absolutely log `ERROR` on request failure. It is definitely a signal we want to watch.
