### ISSUE TITLE
Relayer should log the hash of the ethereum transaction before submitting a CAP block

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cape#952]
When the wallet submits a CAP tx and the corresponding ethereum transaction does not go through the wallet has no way of knowing it can respend the outputs. See Zulip [discussion](https://espresso.zulipchat.com/#narrow/stream/311688-CAPE/topic/Error/near/278767118).

In order to make it easier debugging this kind of issues the relayer should log the hash of the ethereum transaction before submitting a CAP block.

**Comment by pictographer** [comment]
https://github.com/EspressoSystems/cape/pull/959

**Comment by pictographer** [comment]
Closing this because I've created another pull request that is up to date and doesn't need commits pruned out of it. https://github.com/EspressoSystems/cape/pull/973
