### ISSUE TITLE
Relayer sends an empty block periodically

### ISSUE THREAD

**Issue by philippecamacho** [EspressoSystems/cape#958]
[Post](https://discord.com/channels/857206489433112586/916010667117518859/964234879103537183) from @jbearer  on discord:

> When the user wraps some ERC20, all that does is add a pending wrap action to a queue in the contract. The wrap will not actually be finalized (and thus the balance will not show up in the wallet) until some other transaction (mint, transfer, etc.) goes through. This is so that the relayer, and not the user, pays the majority of the gas for processing wraps.
> 
> @clu @min , do we want to handle this in the UI at all? E.g. we could have a popup message alerting the user that it could be some time before they see the results.
> 
> @thedulwhichfox @sveitser there are things we could do on the backend that would make this better. For example, having the relayer submit an empty block every short time interval (minute, maybe?) would mean that you don't have to wait for someone else to submit a transaction, or submit one yourself, just to finalize your pending wrap. (In addition, it would keep the pending deposit queue from growing.)

**Comment by jbearer** [comment]
Note: as an optimization, we can have the relayer check the value of `pendingDeposits` (which is readonly, so free) and only send an empty block if it is nonempty.

**Comment by philippecamacho** [comment]
> Note: as an optimization, we can have the relayer check the value of `pendingDeposits` (which is readonly, so free) and only send an empty block if it is nonempty.

That is a good idea because otherwise we will spend a lot of Goerli eth.

**Comment by philippecamacho** [comment]
@jbearer it is unlikely we have many wrap without users submitting blocks.
